[package]
name = "compiler_package"
version = "1.0.0"
upgrade_policy = "compatible"

[addresses]
# Default addresses (safe fallbacks)
std = "0x1"
aptos_framework = "0x1"
hello = "0x42"

# Allows frontend / user to override
# Example:
# movement = "0x123"

[dependencies]
MoveStdlib = { 
    git = "https://github.com/move-language/move",
    subdir = "language/move-stdlib",
    rev = "main"
}

AptosFramework = {
    git = "https://github.com/aptos-labs/aptos-core",
    subdir = "aptos-move/framework/aptos-framework",
    rev = "main"
}
